### ISSUE TITLE
Module controller missing - Linux & MAC 

### ISSUE THREAD

**Issue by RahulMR42** [lm-sys/RouteLLM#15]
Hi Team ,
Thanks alot for the lib.Unfortunatly we couldn't use it with Linux and Mac 
Version
`routellm==0.1.0`
Error
`
>> from routellm.controller import Controller
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'routellm.controller'
>>> 
`

**Comment by iojw** [comment]
Hi there! Sorry about this, I've just fixed this.

Please try redownloading the latest version from PyPI.
```
pip install "routellm[serve]==0.2.0"
```

**Comment by RahulMR42** [comment]
Looks good now ,thank you.
