### ISSUE TITLE
Can we use 2 ollama models?

### ISSUE THREAD

**Issue by masterchop** [lm-sys/RouteLLM#24]
Why every single framework force everyone to use OpenAI, please allow to use 2 ollama models, for examle llama3:8b and strong model llama3:70b, we also need support for more models what if i want an SQL model in there for sql queries or something else.

**Comment by iojw** [comment]
Hi there! You can indeed use 2 Ollama models following the instructions here: https://github.com/lm-sys/RouteLLM/blob/main/examples/routing_to_local_models.md, just replace the strong model with an Ollama model as well.

However, note that currently, we will still require an OpenAI key for the `mf` and `sw_ranking` routers to generate embeddings. If you would like to avoid this, you can use the `berf` or `causal_llm` classifier instead.

**Comment by masterchop** [comment]
Great ill give it a try when i was testing I did as you asked but i got the error requiring OpenAI model i guess it was for the embeddings ill try berf and casual_llm, thank you

**Comment by iojw** [comment]
Currently, it might still ask you for a key so you can fill in a random value if you're not using `mf` or `sw_ranking`.

I'll look into fixing this.

**Comment by vishwas-palc** [comment]
hi @iojw it still ask for openai api key for random as well

**Comment by masterchop** [comment]
Hello sorry it took me so long to test this out , it is not possible to use the `Controller` client method but using the `OpenAI` client i am able to start the Gradio site.

`
openai_api_key = "EMPTY"
openai_api_base = args.model_url
client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)`

What i dont get is if i dont use the Controller method how do i set the weak and strong models in the documentation provided you this are the 2 methods available.
The client.chat.completions.create has only 1 model available, very confusing sorry.

**Comment by iojw** [comment]
Hi there! Meta has gated Llama 3 behind a user agreement, so you need to make sure to accept the agreement at the link (https://huggingface.co/meta-llama/Meta-Llama-3-8B) using your HF account. Then run `huggingface-cli login` locally to login to your HF account, then this should work.

Let me know if you have any questions!

**Comment by masterchop** [comment]
Yes, I get that but what about Ollama? if you look at the issue title this was pointing to ollama, ollama offer llama3 also, if you look at your documentation https://github.com/lm-sys/RouteLLM/blob/main/examples/routing_to_local_models.md you mention ollama on the solution.

**Comment by iojw** [comment]
The reason is our causal LLM router is using Llama 3 under the hood, and this uses the version of Llama 3 from HF. You could try using the BERT router (`bert`) instead and it will no longer require this.

**Comment by Harinisri29** [comment]
@iojw Hi, I dont want to use any paid models. I want to use only the open source models. So in that case BERT router is the only option? Bcs others are asking for OpenAI key?

**Comment by masterchop** [comment]
> @iojw Hi, I dont want to use any paid models. I want to use only the open source models. So in that case BERT router is the only option? Bcs others are asking for OpenAI key?

did it work for you with BERT? could you please share sample code? i didnt work for me

**Comment by Harinisri29** [comment]
> > @iojw Hi, I dont want to use any paid models. I want to use only the open source models. So in that case BERT router is the only option? Bcs others are asking for OpenAI key?
> 
> did it work for you with BERT? could you please share sample code? i didnt work for me

yeah sure.

client = Controller(
  # List of routers to initialize
  routers=["bert"],
  # The pair of strong and weak models to route to
  strong_model="ollama_chat/llama3.1",
  weak_model="ollama_chat/gemma:2b",

  config = {
    "bert": {
      "checkpoint_path": "routellm/bert_gpt4_augmented"
    }
  },
  # Override API base and key for LLM calls
  api_base=None,
  api_key=None,
  # Display a progress bar for operations
  progress_bar=False,
)

**Comment by masterchop** [comment]
thanks ill give it a try

**Comment by iojw** [comment]
Closing this for now, let me know if you have other questions!
