### ISSUE TITLE
Add support for LLama-3.1 

### ISSUE THREAD

**Issue by goswamig** [lm-sys/RouteLLM#30]
Meta has released [Llama-3.1 ](https://llama.meta.com/docs/model-cards-and-prompt-formats/llama3_1), we should enable support for this in route LLM.

One can start with [config](https://github.com/lm-sys/RouteLLM/blob/88b8dec894809e2a3ed77096623910eb9f861563/routellm/routers/matrix_factorization/model.py#L35) file.

**Comment by iojw** [comment]
It is already possible to use Llama 3.1 with RouteLLM! The key result from our paper is that our routers generalize across different strong / weak model pairs, so I would expect that we get strong performance even when routing between Llama 3 405B / Llama 3 8B using our existing routers.

**Comment by iojw** [comment]
Closing this for now, let me know if you have other questions!
