### ISSUE TITLE
webpage 0.0.0.0:6060 down

### ISSUE THREAD

**Issue by hungvipqt15** [lm-sys/RouteLLM#31]
The webpage at http://0.0.0.0:6060/ might be temporarily down or it may have moved permanently to a new web address although I launch server with routers: ['mf'] completely.
![image](https://github.com/user-attachments/assets/e75f237b-ecae-41ad-b289-fda0b22c8ec5)

**Comment by iojw** [comment]
Hi there! Could you share more details about what you're trying to do? Once you launch the API server, it's expected that you cannot access it from your web browser - it is a OpenAI compatible endpoint.

**Comment by iojw** [comment]
Closing this for now, let me know if you have any other questions.
