### ISSUE TITLE
Are only GPT-4 and Mistral models currently supported for routing? 

### ISSUE THREAD

**Issue by WangRongsheng** [lm-sys/RouteLLM#58]
Are only GPT-4 and Mistral models currently supported for routing?  such as, llama-3, qwen and so on...

**Comment by rqchao** [comment]
Referencing the paper it seems that the routers were trained using GPT-4 and Mistral, but generalize well to and work with any pair of your choice.

**Comment by WangRongsheng** [comment]
thank you
