### ISSUE TITLE
How to train a BERT router?

### ISSUE THREAD

**Issue by CUHKSZzxy** [lm-sys/RouteLLM#60]
Thank you for your excellent work,

I have read the paper and the README instructions.

Could you clarify how to train BERT as a classifier from scratch?  The instructions [this repository](https://github.com/anyscale/llm-router) mainly cover fine-tuning causal LLM through the anyscale API. Is it mandatory to use the Anyscale API, or can we use other offline training/finetuning methods? 

Any help would be appreciated!

**Comment by iojw** [comment]
No, you can definitely use other methods! We describe our approach in detail here: https://arxiv.org/abs/2406.18665.

**Comment by AsalMehradfar** [comment]
Did you / Do you plan to provide your code for training other types of routers? I am curious if there is a setup similar to Causal LLM code for training the other routers.
